package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// now is when a migration is generated, for its file name; tests set it.
var now = time.Now

// A column's SQL on each engine. Text is NOT NULL with an empty default, so sqlc gives
// it a plain string (the gym site's plain columns); a number, a position or
// a date may be unset, as the resource generator's forms expect; required
// makes it NOT NULL.
var columnTypes = map[string]struct{ sqlite, postgres string }{
	"string":   {"text NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"},
	"text":     {"text NOT NULL DEFAULT ''", "text NOT NULL DEFAULT ''"},
	"int":      {"integer", "bigint"},
	"position": {"integer", "bigint"},
	"bool":     {"boolean NOT NULL DEFAULT false", "boolean NOT NULL DEFAULT false"},
	"date":     {"date", "date"},
	"datetime": {"datetime", "timestamptz"},
}

// column is one column's definition, for engine ("sqlite" or "postgresql").
func column(engine, name, typ string, required bool) (string, error) {
	t, ok := columnTypes[typ]
	if !ok {
		return "", fmt.Errorf("%s: type %q isn't string, text, int, position, bool, date or datetime", name, typ)
	}
	sql := t.sqlite
	if engine == "postgresql" {
		sql = t.postgres
	}
	if required && !strings.Contains(sql, "NOT NULL") {
		sql += " NOT NULL"
	}
	return fmt.Sprintf("%q %s", name, sql), nil
}

// generateMigration writes db/migrations/<timestamp>_<name>.sql. As Rails',
// the name shapes it: create_posts makes the table (with id, created_at and
// updated_at), add_email_to_users adds the fields as columns, and anything
// else is an empty up and down to fill in.
func generateMigration(root string, args []string, out io.Writer) error {
	if len(args) < 1 || !columnName.MatchString(args[0]) {
		return errors.New("a migration name in snake_case: create_posts, add_email_to_users")
	}
	name := args[0]
	engine := sqlcEngine(root)
	var cols []string
	var names []string
	for _, spec := range args[1:] {
		parts := strings.Split(spec, ":")
		if len(parts) < 2 || !columnName.MatchString(parts[0]) || len(parts) > 3 || (len(parts) == 3 && parts[2] != "required") {
			return fmt.Errorf("%q isn't column:type[:required]", spec)
		}
		c, err := column(engine, parts[0], parts[1], len(parts) == 3)
		if err != nil {
			return err
		}
		cols, names = append(cols, c), append(names, parts[0])
	}

	var up, down string
	switch table, isCreate := strings.CutPrefix(name, "create_"); {
	case isCreate:
		id := `"id" integer PRIMARY KEY AUTOINCREMENT NOT NULL`
		stamp := "datetime"
		if engine == "postgresql" {
			id, stamp = `"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, "timestamptz"
		}
		all := append(append([]string{id}, cols...), `"created_at" `+stamp+` NOT NULL`, `"updated_at" `+stamp+` NOT NULL`)
		up = fmt.Sprintf("CREATE TABLE %q (\n  %s\n);", table, strings.Join(all, ",\n  "))
		down = fmt.Sprintf("DROP TABLE %q;", table)
	case strings.HasPrefix(name, "add_") && strings.Contains(name, "_to_") && len(cols) > 0:
		table := name[strings.LastIndex(name, "_to_")+len("_to_"):]
		var adds, drops []string
		for i, c := range cols {
			adds = append(adds, fmt.Sprintf("ALTER TABLE %q ADD COLUMN %s;", table, c))
			drops = append([]string{fmt.Sprintf("ALTER TABLE %q DROP COLUMN %q;", table, names[i])}, drops...)
		}
		up, down = strings.Join(adds, "\n"), strings.Join(drops, "\n")
	default:
		up = "-- The change: SQL for this app's engine (" + engine + ")."
		down = "-- What undoes it. Left empty, the migration can't be rolled back."
	}

	dir := filepath.Join(root, "db", "migrations")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	file := now().UTC().Format("20060102150405") + "_" + name + ".sql"
	body := "-- +goose Up\n" + up + "\n\n-- +goose Down\n" + down + "\n"
	if err := os.WriteFile(filepath.Join(dir, file), []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Fprintln(out, "  wrote", filepath.Join("db", "migrations", file))
	return nil
}

// sqlcEngine is the engine sqlc.yaml names: "sqlite" when there's none.
func sqlcEngine(root string) string {
	data, _ := os.ReadFile(filepath.Join(root, "sqlc.yaml"))
	for _, line := range strings.Split(string(data), "\n") {
		if v, ok := strings.CutPrefix(strings.TrimLeft(strings.TrimSpace(line), "- "), "engine:"); ok {
			return strings.Trim(strings.TrimSpace(v), `"'`)
		}
	}
	return "sqlite"
}
