package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/scttymn/gantry/db"
	"github.com/scttymn/gantry/testkit"
)

func at(t *testing.T, when string) {
	t.Helper()
	was := now
	now = func() time.Time { v, _ := time.Parse(time.RFC3339, when); return v }
	t.Cleanup(func() { now = was })
}

func migration(t *testing.T, root string, args ...string) string {
	t.Helper()
	var out, errOut strings.Builder
	if code := run(append([]string{"g", "migration"}, args...), root, &out, &errOut); code != 0 {
		t.Fatalf("exit %d: %s", code, errOut.String())
	}
	return out.String()
}

func TestMigration(t *testing.T) {
	root := app(t)
	at(t, "2026-09-29T12:00:00Z")
	out := migration(t, root, "create_posts", "title:string:required", "body:text", "position:position", "published_on:date", "views:int:required", "draft:bool")
	path := filepath.Join(root, "db", "migrations", "20260929120000_create_posts.sql")
	if !strings.Contains(out, "wrote db/migrations/20260929120000_create_posts.sql") {
		t.Errorf("output: %s", out)
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := `-- +goose Up
CREATE TABLE "posts" (
  "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  "title" text NOT NULL DEFAULT '',
  "body" text NOT NULL DEFAULT '',
  "position" integer,
  "published_on" date,
  "views" integer NOT NULL,
  "draft" boolean NOT NULL DEFAULT false,
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL
);

-- +goose Down
DROP TABLE "posts";
`
	if string(got) != want {
		t.Errorf("got\n%s\nwant\n%s", got, want)
	}

	at(t, "2026-09-29T12:05:00Z")
	migration(t, root, "add_email_to_posts", "email:string", "age:int")
	// Both run, and roll back, on a real database.
	testkit.Migrations(t, os.DirFS(filepath.Join(root, "db", "migrations")), "app_migrations")
	at(t, "2026-09-29T12:10:00Z")
	migration(t, root, "backfill_titles")
	d := testkit.DB(t, func(ctx context.Context, d *db.DB) error {
		return d.Migrate(ctx, os.DirFS(filepath.Join(root, "db", "migrations")), "app_migrations")
	})
	if _, err := d.Write.Exec(`INSERT INTO posts (views, email, created_at, updated_at) VALUES (1, 'a@b.c', '2026-01-01', '2026-01-01')`); err != nil {
		t.Fatal(err)
	}
	var title string
	d.Read.QueryRow(`SELECT title FROM posts`).Scan(&title)
	if title != "" {
		t.Errorf("a string column's default: %q", title)
	}
	other, _ := os.ReadFile(filepath.Join(root, "db", "migrations", "20260929121000_backfill_titles.sql"))
	if !strings.Contains(string(other), "can't be rolled back") {
		t.Errorf("a migration of no known shape:\n%s", other)
	}
}

func TestMigrationPostgres(t *testing.T) {
	root := app(t)
	os.WriteFile(filepath.Join(root, "sqlc.yaml"), []byte("version: \"2\"\nsql:\n  - engine: postgresql\n"), 0o644)
	at(t, "2026-09-29T12:00:00Z")
	migration(t, root, "create_posts", "title:string", "position:position", "seen_at:datetime")
	got, _ := os.ReadFile(filepath.Join(root, "db", "migrations", "20260929120000_create_posts.sql"))
	for _, want := range []string{`"id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`, `"position" bigint,`, `"seen_at" timestamptz,`, `"created_at" timestamptz NOT NULL`} {
		if !strings.Contains(string(got), want) {
			t.Errorf("no %s in\n%s", want, got)
		}
	}
}

func TestMigrationRules(t *testing.T) {
	for _, args := range [][]string{{}, {"CreatePosts"}, {"create_posts", "title"}, {"create_posts", "title:money"}, {"create_posts", "title:string:unique"}} {
		var out, errOut strings.Builder
		if code := run(append([]string{"g", "migration"}, args...), app(t), &out, &errOut); code != 1 || errOut.Len() == 0 {
			t.Errorf("%q: exit %d, %q", args, code, errOut.String())
		}
	}
}

func TestErrorPages(t *testing.T) {
	root := app(t)
	gen := func(args ...string) string {
		var out, errOut strings.Builder
		if code := run(append([]string{"g", "error-pages"}, args...), root, &out, &errOut); code != 0 {
			t.Fatalf("exit %d: %s", code, errOut.String())
		}
		return out.String()
	}
	gen()
	for _, p := range errorPages {
		b, err := os.ReadFile(filepath.Join(root, "public", fmt.Sprintf("%d.html", p.Status)))
		if err != nil || !strings.Contains(string(b), p.Title) || !strings.Contains(string(b), fmt.Sprintf("<title>%s (%d)</title>", p.Title, p.Status)) {
			t.Errorf("%d: %v\n%s", p.Status, err, b)
		}
	}
	// A page the app changed is kept, unless --force.
	mine := filepath.Join(root, "public", "404.html")
	os.WriteFile(mine, []byte("mine"), 0o644)
	os.Remove(filepath.Join(root, "public", "500.html"))
	if out := gen(); !strings.Contains(out, "kept public/404.html") || !strings.Contains(out, "wrote public/500.html") {
		t.Errorf("second run: %s", out)
	}
	if b, _ := os.ReadFile(mine); string(b) != "mine" {
		t.Error("overwrote the app's own 404")
	}
	gen("--force")
	if b, _ := os.ReadFile(mine); string(b) == "mine" {
		t.Error("--force didn't replace it")
	}
}
